version: '3.8'

services:
  api-alunos:
    build:
      context: .
      dockerfile: tests/Dockerfile
    container_name: container-alunos-compose
    ports:
      - "8000:8000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1